---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-conf
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "type": "bridge",
      "name": "mynet",
      "bridge": "eb",
      "isGateway": true,
      "ipMasq": false,
      "ipam": {
      		"type": "host-local",
      		"ranges": [
      			[
      				{
      					"subnet": "10.10.0.0/24",
      					"rangeStart": "10.10.0.20",
      					"rangeEnd": "10.10.0.50"
      				}
      			]
      		],
          "routes": [
            { "dst": "0.0.0.0/0" }
          ],
          "dataDir": "/run/kube-edge/ipam-state"
      	}
    }
