---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: di
spec:
  selector:
    matchLabels:
      app: di
  template:
    metadata:
      labels:
        app: di
      annotations:
        k8s.v1.cni.cncf.io/networks: mynet-conf
    spec:
      nodeSelector:
        edge: "true"
      tolerations:
        - operator: Exists
          effect: NoSchedule
        - operator: Exists
          effect: NoExecute
      containers:
        - name: di
          image: nicolaka/netshoot:latest
          command: ["tail"]
          args: ["/dev/random"]
          imagePullPolicy: Always
