---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-to-cluster
spec:
  selector:
    matchLabels:
      app: proxy-to-cluster
  template:
    metadata:
      labels:
        app: proxy-to-cluster
      annotations:
        k8s.v1.cni.cncf.io/networks: bridge-conf
    spec:
      nodeSelector:
        edge: "true"
      tolerations:
        - operator: Exists
          effect: NoSchedule
        - operator: Exists
          effect: NoExecute
      containers:
        - name: proxy-tcp
          image: alpine/socat
          args: [ "-ddd", "-lh", "-lp", "name", "tcp4-listen:8888,fork", "tcp4-connect:tcp-server:8080" ]
        - name: proxy-udp
          image: alpine/socat
          args: [ "-ddd", "-lh", "-lp", "name", "udp-listen:9999,fork,reuseaddr", "udp4-connect:udp-server:9090" ]
        - name: proxy-http
          image: alpine/socat
          args: [ "-ddd", "-lh", "-lp", "name", "tcp4-listen:8800,fork", "tcp4-connect:http-server:80" ]
        - name: debug
          image: nicolaka/netshoot:latest
          command: ["tail"]
          args: ["/dev/random"]
          imagePullPolicy: Always
      restartPolicy: Always
