---
# tento objekt reprezentuje existující zařízení a aplikace, které na něm běží
# tento objekt nemá vlastní controller, jelikož slouží převážně pro uchování unformací
# při vzniku objektu je testována korektonost definice (jestli existje daný node...)
# dle modu, ve kterém operator běží je nekorektní definice odmítnuta, případně jsou vyhozeny warnings
apiVersion: edge-operator.k8s.dvojak.cz/v1
kind: Device
metadata:
  name: main-device
spec:
  nodeName: minikube            # nazev nodu, ze kterho je device dostupny
  up: true
  ipAddress: 192.168.100.2      # ip adresa nařízení, na které komponenty poslouchají
  components:                   # list komponent (aplikaci), ktere jsou na za59zen9 dostupnost
    - name: component-web
      up: true                  # značí, zda komponenta bezi
      handlers:                 # list endpointu pro aplikaci
        - name: web-page
          protocol: TCP
          port: 80
        - name: web-page-2
          protocol: TCP
          port: 8080
    - name: component-db
      up: false
      handlers:
        - name: db-postgres
          protocol: UDP
          port: 8080
